image: java:8-jdk

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

build:
  stage: build
  script:
    - ./gradlew clean build

build-intellij-2021.1:
  stage: build
  script:
    - ./gradlew clean build -PintellijVersion=2021.1

