name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        intellij-version: [ "2019.1", "2021.1" ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Java JDK
        uses: actions/setup-java@v2.0.0
        with:
          java-version: 8
          distribution: 'adopt'

      - name: Gradle Build
        run: ./gradlew build -PintellijVersion=${{ matrix.intellij-version }}

