name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Java JDK
        uses: actions/setup-java@v2.0.0
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Gradle Build
        run: ./gradlew build

      - uses: actions/upload-artifact@v2
        with:
          name: intellij-actions
          path: build/distributions/*
